### ISSUE TITLE
Rotate Environment Background

### ISSUE THREAD

**Issue by yogiprsetya** [AgileVisionCompany/Simple-Tourism-VR-with-React-360#1]
Can you rotate the Environment.setBackgroundImage ?

inside Wrapper.component.js

**Comment by glibiq** [comment]
You can add "**rotateTransform**" param for the rotation background image, and then you'll be able to change images on all pages but not the default(first) image. To rotate default image you will need to do it in **client.js**, write custom logic because **setBackground()** function does not have **rotateTransform** param or rotate the image itself.
https://facebook.github.io/react-360/docs/environment.html#setbackgroundimageurl-uri-string-options-environmentoptions

And the final code in **Wrapper.component.js** in **changeLocation()** function will look like

`    Environment.setBackgroundImage(asset(`./img/360/${locations[`${location}`].img}`), { rotateTransform: [{ rotateY: '30deg' }, { rotateZ: '90rad' }] }); `

Result:
https://ibb.co/NxrsBLb

**Comment by yogiprsetya** [comment]
> 
> 
> You can add "**rotateTransform**" param for the rotation background image, and then you'll be able to change images on all pages but not the default(first) image. To rotate default image you will need to do it in **client.js**, write custom logic because **setBackground()** function does not have **rotateTransform** param or rotate the image itself.
> https://facebook.github.io/react-360/docs/environment.html#setbackgroundimageurl-uri-string-options-environmentoptions
> 
> And the final code in **Wrapper.component.js** in **changeLocation()** function will look like
> 
> ` Environment.setBackgroundImage(asset(`./img/360/${locations[`${location}`].img}`), { rotateTransform: [{ rotateY: '30deg' }, { rotateZ: '90rad' }] }); `
> 
> Result:
> https://ibb.co/NxrsBLb
